# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('foto', models.URLField(max_length=500)),
                ('habilidad_uno', models.TextField()),
                ('habilidad_dos', models.TextField()),
                ('habilidad_tres', models.TextField()),
            ],
        ),
    ]
